linters:
  # Default linters enabled
  # See: https://golangci-lint.run/usage/linters/#enabled-by-default-linters

  # Additional linters enabled
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - cyclop
    - decorder
    - dogsled
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - gci
    - gochecknoglobals
    - goconst
    - gocritic
    - godot
    - gofmt
    - gomoddirectives
    - goprintffuncname
    - gosec
    - importas
    - makezero
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - nosprintfhostport
    - prealloc
    - predeclared
    - revive
    - tenv
    - testpackage
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
